RoleTop MVC/Models/Orcamento.cs
using System;
using Microsoft.Extensions.Primitives;
using RoleTop_MVC.Models;
using RoleTop_MVC.Enums;

namespace RoleTop_MVC.Models {
    public class Orcamento {
        
        public ulong ID {get;set;}
        public Cliente Cliente {get; set;}
        public DateTime DataEvento { get; set; }
        public string Evento { get; set; }
        public double QuantidadePessoas { get; set; }
        public string Observacao { get; set; }
        public Som Som { get; set; }
        public Iluminacao Iluminacao { get; set; }

        public uint Status {get;set;}

        public Orcamento (DateTime dataEvento, string evento, double quantidadePessoas, string observacao) 
        {
            this.ID = 0;
            this.Cliente = new Cliente();
            this.Iluminacao = new Iluminacao();
            this.Som = new Som();
            this.DataEvento = dataEvento;
            this.Evento = evento;
            this.QuantidadePessoas = quantidadePessoas;
            this.Observacao = observacao;
            this.Status = (uint) StatusPedidos.PENDENTE;
        }

        public Orcamento()
        {
        }
    }
}

RoleTop MVC/ViewModels/OrcamentoViewModel.cs
using System.Collections.Generic;
using RoleTop_MVC.Models;

namespace RoleTop_MVC.ViewModels
{
    public class OrcamentoViewModel
    {
        public List<Iluminacao> Iluminacoes {get; set;}
        public List<Som> Sons {get; set;}
        public string NomeUsuario {get; set;}
        public string Usuario {get; set;}
        public Cliente Cliente {get; set;}
        public List<Orcamento> Eventos { get; set; }
    
    public OrcamentoViewModel()
        {
            this.Iluminacoes = new List<Iluminacao>();
            this.Sons = new List<Som>();
            this.Cliente = new Cliente();
            this.Eventos = new List<Orcamento> ();
        }

    }
}

RoleTop MVC/Controllers/CadastroController.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RoleTop_MVC.Models;
using RoleTop_MVC.Repositorios;
using RoleTop_MVC.ViewModels;

namespace RoleTop_MVC.Controllers {
    public class CadastroController : AbstractController {
        ClienteRepositorio clienteRepositorio = new ClienteRepositorio ();
        public IActionResult Index () {
            switch(ObterUsuarioNomeSession())
            {
                case "":
                    ClienteViewModel clienteviewmodel = new ClienteViewModel(ObterUsuarioNomeSession());
                    return View(clienteviewmodel);
                default:
                    return RedirectToAction("Index","Home");
            }
        }
        [HttpPost]
        public IActionResult Logar(IFormCollection form)
        {
            Cliente cliente = clienteRepositorio.ObterPor(form["email"]);

            HttpContext.Session.SetString(SESSION_CLIENTE_NOME, cliente.Usuario);
            return RedirectToAction("Login","Cliente");
        }
        public IActionResult CadastrarCliente (IFormCollection form) {
            try {
                Cliente cliente = new Cliente (
                    form["usuario"],
                    form["nome"],
                    form["email"],
                    form["telefone"],
                    form["cpf"],
                    DateTime.Parse (form["dataNascimento"]),
                    form["senha"]);

                clienteRepositorio.Inserir (cliente);
                HttpContext.Session.SetString(SESSION_CLIENTE_NOME, cliente.Usuario);
                    return RedirectToAction("Login","Cliente");
            } catch (Exception e) {
                return View ("Erro");
            }
        }
    }
}

RoleTop MVC/Controllers/OrcamentoController.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RoleTop_MVC.Models;
using RoleTop_MVC.Repositorios;
using RoleTop_MVC.ViewModels;

namespace RoleTop_MVC.Controllers {
    public class OrcamentoController : AbstractController {
        OrcamentoRepositorio orcamentoRepositorio = new OrcamentoRepositorio ();
        IluminacaoRepositorio iluminacaoRepositorio = new IluminacaoRepositorio ();
        SomRepositorio somRepositorio = new SomRepositorio ();
        ClienteRepositorio clienteRepositorio = new ClienteRepositorio ();
        
        public IActionResult Index () {
            var iluminacoes = iluminacaoRepositorio.ObterTodos();
            var sons = somRepositorio.ObterTodos();

            OrcamentoViewModel orcamento = new OrcamentoViewModel();
            orcamento.Iluminacoes = iluminacoes;
            orcamento.Sons = sons;

            var usuarioLogado = ObterUsuarioSession();
            var nomeUsuarioLogado = ObterUsuarioNomeSession();
            if(!string.IsNullOrEmpty(nomeUsuarioLogado)){
                orcamento.NomeUsuario = nomeUsuarioLogado;
            }

            var clienteLogado = clienteRepositorio.ObterPor(usuarioLogado);
            if(clienteLogado != null){
                orcamento.Cliente = clienteLogado;
            }
            ClienteViewModel orcamentoViewModel = new ClienteViewModel  (ObterUsuarioNomeSession());
            return View(orcamentoViewModel);
        }
        public IActionResult CriarEvento () 
        {
            switch (ObterUsuarioNomeSession ()) {
                case "Administrador":
                    return RedirectToAction ("Dashboard", "Administrador");
                case "":
                    return RedirectToAction ("Index", "Home");
                default:
            ClienteViewModel orcamentoViewModel = new ClienteViewModel(ObterUsuarioNomeSession());
            return View(orcamentoViewModel);
            }
        }

        [HttpPost]
        public IActionResult CriarEvento(IFormCollection form)
        {
            try
            {
                Cliente cliente = new Cliente(
                    form["usuario"]
                );
                Orcamento evento = new Orcamento(
                    DateTime.Parse(form["dataEvento"]),
                    form["evento"],
                    int.Parse(form["quantidadePessoas"]),
                    form["observacao"]
                );
                Som som = new Som(
                    form["som"]
                );
                Iluminacao iluminacao = new Iluminacao(
                    form["iluminacao"]);
                    
                cliente.Usuario = ObterUsuarioNomeSession();
                orcamentoRepositorio.Inserir(evento);
                
                return RedirectToAction("Index","Cliente");
                

            }catch(Exception e)
            {
                return View("Deu Ruim");
            }
        }
    }
}

RoleTop MVC/Views/Orcamento/Index.cshtml
@model RoleTop_MVC.ViewModels.ClienteViewModel
<main>
<form method="POST" action='@Url.Action("Registrar", "Orcamento")'>
<div class="section-container">
        <div class="content">
        <section id="Orcamento">

                <h1>Orçamento</h1>


                <section id="usuario">
                <label for="usuario">Organizador</label>
                <br />
                <input type="text" name="usuario" required="required">
            </section>

            <section id="data">
                <label for="data">Data do evento</label>
                <br />
                <input type="date" name="dataEvento" required="required">
            </section>

            <section id="evento">
                <label for="evento">Evento</label>
                <br />
                <input type="text" name="evento" required="required">
            </section>

            <section id="pessoas">
                <label for="pessoas">Quantidade de pessoas</label>
                <br />
                <input type="number" name="quantidadePessoas" required="required">
            </section>

            <section id="obs">
                <label for="obs">Observações</label>
                <br />
                <input type="text" name="observacao" required="required">
            </section>
                <div>
                    <label for="som">Som</label>
                    <select id="som" name="som" required>
                        <option value="" disabled selected>Adicionar</option>
                        @foreach (var s in Model.Sons)
                        {
                            <option value=@s.Tipo>@s.Tipo por @s.Preco</option>
                        }
                    </select>
                </div>
                <div>
                    <label for="iluminacao">Iluminação</label>
                    <select id="iluminacao" name="iluminacao">
                        <option value="" disabled selected>Adicionar</option>
                        @foreach (var i in Model.Iluminacoes)
                        {
                            <option value="@i.Tipo">@i.Tipo por @i.Preco</option>
                        }
                    </select>
                </div>

                <section id="enviar-login">
                @if(string.IsNullOrEmpty(@Model.NomeUsuario))
                {
                <a href='@Url.Action("Index", "Cadastro")'>Finalizar Orçamento</a>
                }else
                {
                <a type="submit" value="Enviar">Finalizar Orçamento</a>
                }
                </section>

</form>
        </section>
        </div>
</div>